name: Upstream Mirror Sync

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: '29 * * * *' # hourly at :29 UTC

permissions:
  contents: write

concurrency:
  group: upstream-mirror-sync
  cancel-in-progress: false

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/Kryssie6985/pantheon-ladderworks.github.io.git || true
          git fetch upstream --prune --tags

      - name: Mirror branches from upstream -> origin
        run: |
          git push origin "refs/remotes/upstream/*:refs/heads/*" --force

      - name: Mirror tags from upstream -> origin
        run: |
          git push origin --tags --force

      - name: Restore this workflow after force-push
        run: |
          mkdir -p .github/workflows
          cat > .github/workflows/upstream-sync.yml <<'YAML'
          name: Upstream Mirror Sync

          on:
            workflow_dispatch:
            push:
              branches:
                - master
            schedule:
              - cron: '29 * * * *' # hourly at :29 UTC

          permissions:
            contents: write

          concurrency:
            group: upstream-mirror-sync
            cancel-in-progress: false

          jobs:
            mirror:
              runs-on: ubuntu-latest
              steps:
                - name: Checkout fork
                  uses: actions/checkout@v4
                  with:
                    fetch-depth: 0

                - name: Configure git identity
                  run: |
                    git config user.name "github-actions[bot]"
                    git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

                - name: Add upstream and fetch
                  run: |
                    git remote add upstream https://github.com/Kryssie6985/pantheon-ladderworks.github.io.git || true
                    git fetch upstream --prune --tags

                - name: Mirror branches from upstream -> origin
                  run: |
                    git push origin "refs/remotes/upstream/*:refs/heads/*" --force

                - name: Mirror tags from upstream -> origin
                  run: |
                    git push origin --tags --force
          YAML
          git add .github/workflows/upstream-sync.yml
          git commit -m "ci: ensure upstream mirror workflow persists"
          git push
